source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'
use_frameworks!

target 'iosApp' do
  pod 'GoogleMaps'
  pod 'FirebaseMessaging', '~> 10.29.0'
  pod 'FirebaseCore', '~> 10.29.0'
  pod 'FirebaseFirestore', '~> 10.29.0'
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
    end
  end
end
