source 'https://cdn.cocoapods.org/'

# Keep this in sync with shared/build.gradle.kts.
platform :ios, '15.0'
use_frameworks!

target 'iosApp' do
  pod 'GoogleMaps'
  pod 'FirebaseMessaging'
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
